# Generated by Django 6.0.3 on 2026-03-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('provider', 'Service Provider')], default='client', max_length=20),
        ),
    ]
